---
title: "Reoirt"
author: "Group 24"
date: "Week 7"
output: pdf_document
number_sections: yes
header-includes: \usepackage{hyperref}
---

Group 24

##Introduction

##Part 1: Data Design and Implementation

In this report, we assume that the E-commerce platform mainly sells IT products in the United Kingdom and does not have an international shipment policy.
Furthermore, company policy is that product only has one promotion during a year, “Product_ID” is identified based on “Supplier_ID”, which means supplier only has one “Product_ID” for one product.
Also, money collected by e-commerce company is distributed later to supplier.

There are 7 entities:

1.Buyer: Represents the customers who create an account to place orders on the online shopping platform.

2.Supplier: Represents the sellers who create an account to sell products on the platform

3.Product: Represents the set of products available for purchase on the platform.

4.Transaction: Represents product orders placed by customers.

5.Promotion: Represents product promotions to attract willing customers.

6.Shipper: Represents Shipper information.

7.Reviews: Represents the reviews made by the customer once the product is received.

\[picture\]

##Part 2: Data generation
