

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,comment = NA)
library(readr)
```

```{r}
library(readr)
```

# File Suffix
```{r readr,attr.source='.numberLines'}
# read files from 'data' folder
project_files <- list.files("data/")
project_files

```

```{r block2,attr.source='.numberLines'}
suffix <- ".csv"
project_files <- gsub(suffix,"",project_files)
project_files

```

```{r address}
# Address
address_data <- read_csv("data/Address.csv")
```

```{r buyer}
# Buyer
buyer_data <- read_csv("data/Buyer.csv")
```

```{r colnames}
colnames(address_data)
colnames(buyer_data)
```

# Number of rows and columns in the dataset
```{r loop,message=FALSE,warning=FALSE,attr.source='.numberLines'}

all_files <- list.files("data/")

for (variable in all_files) {
  this_filepath <- paste0("data/",variable)
  this_file_contents <- readr::read_csv(this_filepath)
  
  number_of_rows <- nrow(this_file_contents)
  number_of_columns <- ncol(this_file_contents)
  
  print(paste0("The file: ",variable,
              " has: ",
              format(number_of_rows,big.mark = ","),
              " rows and ",
              number_of_columns," columns"))
}
```

# Check if the first column of each file is a primary 
```{r checkprimary,message=FALSE,warning=FALSE,attr.source='.numberLines'}

for (variable in all_files) {
  this_filepath <- paste0("data/",variable)
  this_file_contents <- readr::read_csv(this_filepath)
  number_of_rows <- nrow(this_file_contents)
  
  print(paste0("Checking for: ",variable))
  
  print(paste0(" is ",nrow(unique(this_file_contents[,1]))==number_of_rows))
}

```

# Creating Database
```{r loadsqlite,warning=FALSE,error=FALSE,message=FALSE,attr.source='.numberLines'}
# Load the library
library(RSQLite)

#setup the connection
connection <- RSQLite::dbConnect(RSQLite::SQLite(),"ecommerce.db")

#for (variable in all_files) {
#  this_filepath <- paste0("data/",variable)
#  this_file_contents <- readr::read_csv(this_filepath)

#  table_name <- gsub(".csv","",variable)
  #Remove prefix and suffix 
#  table_name <- gsub("_Data","",table_name)
  # table_name <- variable
  
#  RSQLite::dbWriteTable(connection,table_name,this_file_contents,overwrite=TRUE)
  
#}
```


```{r}
dbExecute(connection, 
"CREATE TABLE address (
  Address_ID INT PRIMARY KEY, 
  'House Number' INT,
  'House Name' VARCHAR(50),
  Street VARCHAR(50),
  City VARCHAR(20) NOT NULL,
  County VARCHAR(20),
  Postcode VARCHAR(10)
) ; " )
```
```{r}
# Write to existing table - address
RSQLite::dbWriteTable(connection,"address",address_data,append=TRUE,rowname=FALSE)
```

```{r}


dbExecute(connection, 
"CREATE TABLE 'buyer' (
  'buyer_id' INT PRIMARY KEY, 
  'first_name' VARCHAR(250) NOT NULL,
  'last_name' VARCHAR(250),
  'date_of_birth' DOUBLE,
  'Address_ID' INT,
  FOREIGN KEY('Address_ID') REFERENCES address('Address_ID')
) ; " )
```



```{r}
# Write to existing table - buyer
RSQLite::dbWriteTable(connection,"buyer",buyer_data,append=TRUE,rowname=FALSE)
```

```{r listtables}
# Get a list of tables from the database that we already 
# created
RSQLite::dbListTables(connection)

```




```{r defineconnection}
# we will use the name of this variable to 
# set up sql output in the rmd file
#my_connection <- RSQLite::dbConnect(RSQLite::SQLite(),"ecommerce.db")
```


```{sql connection=connection}
SELECT * FROM address
```
```{sql connection=connection}
SELECT * FROM buyer
```



```{r listtables}
# Get a list of tables from the database that we already 
# created
RSQLite::dbListTables(connection)

```


# Disconnect
```{r disconnect}
# Disconnect from the database using the connection variable that we setup 
# before
RSQLite::dbDisconnect(connection)

```